require('core.plugin_config.lualine')
require('core.plugin_config.nvim-tree')
require('core.plugin_config.bufferline')
require('core.plugin_config.lsp_config')
require('core.plugin_config.completion')
require('core.plugin_config.mini_bufremove')
require('core.plugin_config.telescope')
